#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: consumer-management-secrets
  namespace: mvd-001-demo
spec:
  encryptedData:
    EDC_XAPIKEY: AgBCrUd33TxbaM5/TbKp/tomW+lVjAw/VyPIOUq+kRAVFxxIsii7f6qZLgI+SfLH27JfepzE/pyrhzX+bCKSfQFcwpiDIdNj8cvcQNoxBVC2+ykm1GR6+Q/PbdAEPDeAlbs8DD5Qvhftx3rOn5+zSz1KywTL24oqDbBXbe7q+1ZvMWpcWB0w0t4EJt6Qo4hr+gfsDgJ28WLq9kJxhMgeyfbLVX2VPo6sTZccUn99ndBcKhZlAuIc8s/oEtmPzZ2cy+ZyQeTYFVlSvxnVLpvxAGA6BZSH+H6NjzyalzP+6WZdnsVANaM+ANLSgXzSAzq+MRxMVh0tIUtWuTWhhK0SOEGv/JOsyqx5tyIJVsK+mF6fxUfqFR7S5rnauwsl8h6QpG5keiAgrbvNcSpmoc5h6njMAFT6pvIJOrK49akV33/crY/HJqJdo9yLJ2vqghkEYJKiPJZaArvlf/8ewQudBbemnhHi2S5G1klrpPszuEe0QPGrP3ezqYd5cu9yyHoSyG5vaPfIa94IFJqI6705fPy8gWksOA5IPxR8bb3FUMf5X6aBsQCiNh/804o3BmTdXWmZab3ojsDRa2x9rPgQ9OR4YMPolmReszz9Ii+oOQmMREkhR4rGKpkX/yO4Kd+XFJGeKk/ywdDDfoQQaKjlju/DfTUZktYq0DUG+uR6Ta0bKjtgz9HcA2171f29/TzJXNhTy3/jyet+jA==
    FH_CATALOG_SECRETKEY: AgA/QKp7bEyFeo7+IhFoXWVT+7JhvR0Vb4WC4XAAu60Qg1DAcnSETo0RX8H5Nbr9sHcUlte4su5wMV/AZm7xNULYTbJuNLUP/vRupCOydFzHMHlMLdUh7vhyeI6NHgY67YqRU2ZLjOejc0M4HRChUXatVsDBIAuUcQj+aDpvkLvd2vBpLAtieRUG8uX3pGfa4JmYddqyAIyeFEUkOEaYb95r2dKhPkAy4Qnyapsy9g62i+UzAPlhkxyaMMBaiuyb2K8K+F5KquMZc/PV3/AOAWcsG3BQxksBSOr8R8HbPNFDErlCICad8i9Ys2WLi0dQFAcaPkHNo4ogGXnSt9SYV9v4aktB/57IkzFb5D2uy4BgkqKPYXE1L+Qb4XO2Et08vK3/rQGMb33EEc4jxUYdV/TCQYaiCH9m8rl8lJZ/QqdekezpGd8Ql3unM8pNlMUwC2rmW2kZ+Gs/5rz47hWJfN9z4hpakzK9V6IYNFr9bj/ylWAleswdGoUhbOJynVJxLv43DE4Rn6DUnLxaqC0Zp9928I5A1lIxuuun/qSwSlQJhhtjpPTxNz7/YGmIUUZ/YPIhVq2vwI+f7WsXhM4KorSBleOrLNhWjrOBDaVmrzObG41FQOs8KoeGVILWW4xMFPAaHuhlInpHv2wLidE8d8v4KAPEffIehYt1MOhh7khJoRW9c1kOuWAfvl1iz04mjA1GTDoT77Kq0JVMvhsye8hVPfWH6bQebP9mTxJ5buZdeHFqM7E6koUMFeEu2FzSfLXniADdRaY30AfOIS7bRp8Y5pWFh/kcDBSZvG+b1BiouP/6/oQarcC4TfgF6O/Bv89jG+vEXcOFWZnzuSXnlliCORO9miP3lac534AgT1ePY8msGcGc
  template:
    metadata:
      creationTimestamp: null
      name: consumer-management-secrets
      namespace: mvd-001-demo
    type: Opaque
